### PR TITLE
Docs: Add information about auto-retry to browser client docs

### PR DESCRIPTION
**Pull request by jeppester**
### ❓ Type of change

- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Add documentation for the auto-retry functionality introduced by https://github.com/japa/browser-client/pull/5

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by thetutlage** [comment]
Hello @jeppester is this PR ready for review?

**Comment by jeppester** [comment]
> Hello @jeppester is this PR ready for review?

I was something I quickly threw together when I had a short time window. So I didn't feel confident enough about it to mark it as "ready for review".

I'll let you know when I've had a second look at it.

**Comment by jeppester** [comment]
@thetutlage I believe this is now ready for review

**Comment by thetutlage** [comment]
Cool. Looks good 👍

**Pull request merged**
